Journal-Limpet/Controllers/JournalController.cs
using Hangfire;
using Journal_Limpet.Jobs;
using Journal_Limpet.Jobs.SharedCode;
using Journal_Limpet.Shared.Database;
using Journal_Limpet.Shared.Models;
using Journal_Limpet.Shared.Models.Journal;
using Journal_Limpet.Shared.Models.User;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Configuration;
using Minio;
using StackExchange.Exceptional;
using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net.Http;
using System.Security.Claims;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;

namespace Journal_Limpet.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    [Authorize]
    public class JournalController : ControllerBase
    {
        private readonly MSSQLDB _db;
        private readonly IConfiguration _configuration;
        private readonly IMemoryCache _memoryCache;
        private readonly MinioClient _minioClient;
        private readonly IHttpClientFactory _httpClientFactory;

        public JournalController(MSSQLDB db, IConfiguration configuration, IMemoryCache memoryCache, MinioClient minioClient, IHttpClientFactory httpClientFactory)
        {
            _db = db;
            _configuration = configuration;
            _memoryCache = memoryCache;
            _minioClient = minioClient;
            _httpClientFactory = httpClientFactory;
        }

        [HttpGet("info")]
        public async Task<JsonResult> GetInfo([FromQuery] string uuid)
        {
            var user = (await _db.ExecuteListAsync<Profile>(
                "SELECT * FROM user_profile WHERE user_identifier = @id",
                new SqlParameter("@id", Guid.Parse(uuid))))
                .FirstOrDefault();

            if (user != null)
            {
                // This UUID has a user!
                return new JsonResult(user);
            }

            return new JsonResult(new
            {
                success = false,
                error = "Missing account"
            });
        }

        [HttpGet("authenticate")]
        [AllowAnonymous]
        public async Task<IActionResult> Authenticate()
        {
            var code = Request.Query["code"];
            var state = Request.Query["state"];

            if (!_memoryCache.TryGetValue("frontierLogin-" + HttpContext.Connection.RemoteIpAddress.ToString(), out string storedState))
            {
                return BadRequest("Could not find login token, try again");
            }

            if (state != storedState)
            {
                return Unauthorized("Invalid state, please relogin");
            }

            var redirectUrl = string.Format("{0}://{1}{2}", Request.Scheme, Request.Host, Url.Content("~/api/journal/authenticate"));

            var c = _httpClientFactory.CreateClient();

            var formData = new Dictionary<string, string>();
            formData.Add("grant_type", "authorization_code");
            formData.Add("code", code);
            formData.Add("client_id", _configuration["EliteDangerous:ClientId"]);
            formData.Add("client_secret", _configuration["EliteDangerous:ClientSecret"]);
            formData.Add("state", state);
            formData.Add("redirect_uri", redirectUrl);

            var result = await c.PostAsync("https://auth.frontierstore.net/token", new FormUrlEncodedContent(formData));

            var tokenInfo = JsonSerializer.Deserialize<OAuth2Response>(await result.Content.ReadAsStringAsync());

            if (result.IsSuccessStatusCode)
            {
                c.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", tokenInfo.AccessToken);

                result = await c.GetAsync("https://auth.frontierstore.net/me");

                var profile = JsonSerializer.Deserialize<FrontierProfile>(await result.Content.ReadAsStringAsync());

                var settings = new Settings
                {
                    AuthToken = tokenInfo.AccessToken,
                    TokenExpiration = DateTimeOffset.UtcNow.AddSeconds(tokenInfo.ExpiresIn),
                    RefreshToken = tokenInfo.RefreshToken,
                    FrontierProfile = profile
                };

                // Move this so a service later
                var matchingUser = (await _db.ExecuteListAsync<Profile>(@"
SELECT *
FROM user_profile
WHERE JSON_VALUE(user_settings, '$.FrontierProfile.customer_id') = @customerId",
new SqlParameter("customerId", profile.CustomerId))
                ).FirstOrDefault();

                if (matchingUser != null)
                {
                    if (string.IsNullOrWhiteSpace(matchingUser.UserSettings.JournalLimpetAPIToken))
                    {
                        settings.JournalLimpetAPIToken = Guid.NewGuid().ToString();
                    }

                    // Update user with new token info
                    await _db.ExecuteNonQueryAsync("UPDATE user_profile SET user_settings = @settings, last_notification_mail = NULL, skip_download = 0 WHERE user_identifier = @userIdentifier",
                        new SqlParameter("settings", JsonSerializer.Serialize(settings)),
                        new SqlParameter("userIdentifier", matchingUser.UserIdentifier)
                    );

                    matchingUser.UserSettings = settings;
                }
                else
                {
                    settings.JournalLimpetAPIToken = Guid.NewGuid().ToString();

                    // Create new user
                    matchingUser = await _db.ExecuteSingleRowAsync<Profile>("INSERT INTO user_profile (user_settings) OUTPUT INSERTED.* VALUES (@settings)",
                        new SqlParameter("settings", JsonSerializer.Serialize(settings))
                    );

                    var userCount = await _db.ExecuteScalarAsync<long>("SELECT COUNT_BIG(user_identifier) FROM user_profile WHERE deleted = 0");

                    await SSEActivitySender.SendGlobalActivityAsync("A new user has registered!", $"We now have {userCount:N0} users registered!");
                    await SSEActivitySender.SendStatsActivityAsync(_db);

                    BackgroundJob.Enqueue(() => JournalDownloader.DownloadJournalAsync(matchingUser.UserIdentifier, null));
                }

                var claims = new List<Claim>()
                {
                    new Claim(ClaimTypes.Name, matchingUser.UserIdentifier.ToString())
                };

                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                var authProperties = new AuthenticationProperties
                {
                    AllowRefresh = true,
                    IsPersistent = false,
                    IssuedUtc = DateTimeOffset.UtcNow
                };

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), authProperties);

                return LocalRedirect("~/Index");
            }
            else
            {
                return new JsonResult(await result.Content.ReadAsStringAsync());
            }
        }

        [HttpGet("{journalDate}/download")]
        public async Task<IActionResult> DownloadJournalAsync(DateTime journalDate)
        {
            var journal = await JournalLoader.GetJournalForDate(_db, _minioClient, User, journalDate);

            if (journal.fileName == null)
                return NotFound();

            MemoryStream unzippedContent = new MemoryStream(Encoding.UTF8.GetBytes(journal.journalContent));
            return File(unzippedContent, "application/octet-stream", journal.fileName);
        }

        [HttpGet("all-journals/download")]
        public async Task<IActionResult> DownloadAllJournalsAsync()
        {
            var allUserJournals = await _db.ExecuteListAsync<UserJournal>("SELECT * FROM user_journal WHERE user_identifier = @user_identifier AND last_processed_line_number > 0 ORDER BY journal_date ASC",
                new SqlParameter("user_identifier", User.Identity.Name));

            byte[] outBytes;

            using (var ms = new MemoryStream())
            {
                using (var archive = new ZipArchive(ms, ZipArchiveMode.Create, true))
                {
                    foreach (var journal in allUserJournals)
                    {
                        var journalData = await JournalLoader.GetJournalForDate(_db, _minioClient, User, journal.JournalDate.Date);
                        var fileEntry = archive.CreateEntry(journalData.fileName);

                        using var fs = fileEntry.Open();
                        using var sw = new StreamWriter(fs);
                        {
                            await sw.WriteAsync(journalData.journalContent);
                        }
                    }
                }
                ms.Seek(0, SeekOrigin.Begin);

                outBytes = ms.ToArray();
            }

            return File(outBytes, "application/zip", $"JL-JournalBackup-{DateTime.Now.Date.ToShortDateString()}.zip");
        }

        [HttpGet("logout")]
        public async Task<IActionResult> SignOut()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return LocalRedirect("~/Index");
        }

        [Route("exceptions/{path?}/{subPath?}")]
        public async Task Exceptions()
        {
            if (User.Identity.IsAuthenticated && User.Identity.Name.Equals(_configuration["ExceptionUserId"], StringComparison.InvariantCultureIgnoreCase))
            {
                await ExceptionalMiddleware.HandleRequestAsync(HttpContext).ConfigureAwait(false);
            }
        }
    }
}

Journal-Limpet/Controllers/RssController.cs
using Markdig;
using Markdig.Extensions.Yaml;
using Markdig.Parsers;
using Markdig.Syntax;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;

namespace Journal_Limpet.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class RssController : ControllerBase
    {
        [Route("")]
        public IActionResult NewsFeed()
        {
            var newsRss = new RssFeed
            {
                Title = "Journal Limpet: News feed",
                Description = "This is the Journal Limpet news feed",
                Link = Url.RouteUrl("", null, HttpContext.Request.Scheme, HttpContext.Request.Host.ToString())
            };

            var newsFiles = Directory.GetFiles(Path.Combine(Environment.CurrentDirectory, "News"), "*.md");

            var mdPipeline = new MarkdownPipelineBuilder().UseYamlFrontMatter().Build();

            foreach (var file in newsFiles)
            {
                var fileContent = System.IO.File.ReadAllText(file);
                var mdFile = Markdown.Parse(fileContent, mdPipeline);

                var frontMatter = (YamlFrontMatterBlock)mdFile.FirstOrDefault(b => b.Parser is YamlFrontMatterParser);
                var itemTitle = ((HeadingBlock)mdFile.FirstOrDefault(b => b.Parser is HeadingBlockParser))?.Inline.FirstOrDefault();

                var data = frontMatter.Lines.Lines.Select(l => l.Slice.ToString().Split(':', 2).Select(s => s.Trim()).ToList()).Where(s => s.Count > 1).ToDictionary(s => s[0], s => s[1]);

                var clearText = Markdown.ToPlainText(fileContent, pipeline: mdPipeline);
                var htmlText = Markdown.ToHtml(fileContent, pipeline: mdPipeline);

                var fileName = new FileInfo(file).Name;

                var newsItem = new RssFeedItem
                {
                    Title = itemTitle.ToString(),
                    Description = htmlText,
                    Link = Url.Page("/News", null, null, HttpContext.Request.Scheme, HttpContext.Request.Host.ToString()) + "/" + fileName.Replace(".md", "")
                };

                if (data.ContainsKey("pubdate"))
                {
                    if (DateTimeOffset.TryParse(data["pubdate"], out var articleTime))
                    {
                        newsItem.PubDate = articleTime;
                    }
                }

                if (data.ContainsKey("category"))
                {
                    newsItem.Category = data["category"];
                }

                newsRss.FeedItems.Add(newsItem);
            }

            return Content(newsRss.ToString(), "application/rss+xml");
        }
    }

    public class RssFeed
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public string Link { get; set; }

        public List<RssFeedItem> FeedItems { get; set; } = new List<RssFeedItem>();

        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();

            // RSS header
            sb.AppendLine("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
            sb.AppendLine("<rss version=\"2.0\" xmlns:atom=\"http://www.w3.org/2005/Atom\">");

            // Channel info
            sb.AppendLine("<channel>");
            sb.AppendLine($"  <title>{Title}</title>");
            sb.AppendLine($"  <link>{Link}</link>");
            sb.AppendLine($"  <atom:link href=\"{Link}\" rel=\"self\" type=\"application/rss+xml\" />");
            sb.AppendLine($"  <description>{Description}</description>");

            // All the news items
            foreach (var item in FeedItems)
            {
                sb.AppendLine(ReplaceVariables(item.ToString()));
            }

            // End of channel and RSS
            sb.AppendLine("</channel>");
            sb.AppendLine("</rss>");

            return sb.ToString();
        }

        private string ReplaceVariables(string feedItem)
        {
            return feedItem
                .Replace("$rssUrl$", Link);
        }
    }

    public class RssFeedItem
    {
        public DateTimeOffset PubDate { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public Guid Guid
        {
            get
            {
                using (MD5 md5 = MD5.Create())
                {
                    return new Guid(md5.ComputeHash(Encoding.UTF8.GetBytes(Title)));
                }
            }
        }
        public string Link { get; set; }

        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();

            sb.AppendLine("  <item>");
            sb.AppendLine($"    <title>{Title}</title>");
            sb.AppendLine($"    <guid isPermaLink=\"false\">{Guid}</guid>");
            sb.AppendLine($"    <pubDate>{(PubDate.ToString("ddd',' d MMM yyyy HH':'mm':'ss", new CultureInfo("en-US")) + " " + PubDate.ToString("zzzz").Replace(":", ""))}</pubDate>");
            sb.AppendLine($"    <category>{Category}</category>");
            sb.AppendLine($"    <link>{Link}</link>");
            sb.AppendLine($"    <description><![CDATA[{Description}]]></description>");
            sb.Append("  </item>");

            return sb.ToString();
        }
    }
}

Journal-Limpet/Pages/About.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using System.Net.Http;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace Journal_Limpet.Pages
{
    public class AboutModel : PageModel
    {
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly IConfiguration _configuration;

        public PatreonGoal Goal { get; set; } = null;

        public AboutModel(IConfiguration configuration, IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
            _configuration = configuration;
        }

        public async Task OnGetAsync()
        {
            try
            {
                var hc = _httpClientFactory.CreateClient();
                hc.DefaultRequestHeaders.UserAgent.ParseAdd("Journal-Limpet");
                var res = await hc.GetStringAsync(_configuration["Patreon:GoalApiUrl"]);
                Goal = JsonSerializer.Deserialize<PatreonGoal>(
                        JsonDocument.Parse(res).RootElement
                            .GetProperty("data")
                            .GetProperty("attributes")
                            .GetRawText()
                        );
            }
            catch
            {
                Goal = null;
            }
        }

        public class PatreonGoal
        {
            [JsonPropertyName("amount_cents")]
            public long AmountCents { get; set; }
            [JsonPropertyName("completed_percentage")]
            public int CompletedPercentage { get; set; }
            [JsonPropertyName("currency")]
            public string Currency { get; set; }
        }
    }
}

Journal-Limpet/Pages/FAQ.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Journal_Limpet.Pages
{
    public class FAQModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Journal-Limpet/Pages/LiveAccountLog.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Journal_Limpet.Pages
{
    [Authorize]
    public class LiveAccountLogModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Journal-Limpet/Pages/About.cshtml
@page
@model Journal_Limpet.Pages.AboutModel
@{
    ViewData["title"] = "About us";
}

<h1>About Journal Limpet</h1>
<p><strong>Journal Limpet</strong> is a open source project by NoLifeKing85 (<a href="https://twitter.com/NoLifeKing85" target="_blank" rel="nofollow">Twitter</a>, <a href="https://twitch.tv/NoLifeKing85" target="_blank" rel="nofollow">Twitch</a>)</p>
<p>
    The purpose of this web application is to give the commanders of <a href="https://www.elitedangerous.com/" target="_blank" rel="nofollow">Elite: Dangerous</a> the ability to download their journals no matter where they are,
    and give them the option to push their journals automatically to services like EDSM, EDDN and so on
</p>

<h2>The technology used to run this site</h2>
<p>To be fully transparent of what tech we use to run this site, I thought I might list the dependencies we use</p>
<ul>
    <li><a href="https://www.hangfire.io/" target="_blank" rel="nofollow">Hangfire</a> (for background jobs)</li>
    <li><a href="https://min.io/" target="_blank" rel="nofollow">MinIO</a> (for journal storage)</li>
    <li><a href="https://sendgrid.com" target="_blank" rel="nofollow">SendGrid</a> (for sending email notifications)</li>
    <li><a href="https://nickcraver.com/StackExchange.Exceptional/" target="_blank" rel="nofollow">StackExchange.Exceptional</a> (for catching exceptions in a better way)</li>
    <li><a href="https://stackexchange.github.io/StackExchange.Redis/" target="_blank" rel="nofollow">StackExchange.Redis</a> (for caching)</li>
    <li><a href="http://www.thepollyproject.org/" target="_blank" rel="nofollow">Polly</a> (for resilience and transient-fault-handling)</li>
    <li><a href="https://dot.net" target="_blank" rel="nofollow">.NET Core</a> (for hosting the website and running the code..)</li>
    <li><a href="https://github.com/xoofx/markdig" target="_blank" rel="nofollow">Markdig</a> (for Markdown/Frontmatter parsing for the news..)</li>
</ul>

<h2>The cost of maintaining this service</h2>
<p>
    Since I planned ahead while building this, I have a whopping 2 dedicated servers for the purpose of storing your journals.
    One database/storage server, that keeps all the journals in a safe place, and one webserver that runs the website.
</p>
@if (Model.Goal != null)
{
    <p>The running costs of these 2 servers amount to around @(Model.Goal.AmountCents / 100) @Model.Goal.Currency / month, so it ain't that bad. :)</p>
    @if (Model.Goal.CompletedPercentage >= 5)
    {
        <p>
            With the current help from my <a href="https://www.patreon.com/bePatron?u=48387676" target="_blank">Patreon</a>, we get about @Model.Goal.CompletedPercentage % of the total running costs, thank you so much everyone for helping out &lt;3
        </p>
    }
}
else
{
    <p>The running costs of these 2 servers amount to around 100 EUR / month, so it ain't that bad. :)</p>
    <p>
        If you want to help contribute to the continued service, please check out our <a href="https://www.patreon.com/bePatron?u=48387676" target="_blank">Patreon</a>.
    </p>
}

<h2>Reach out to us</h2>
<p>If you ever want to reach out to us, in case you have a great idea, question or want to report something, there are ways to get a hold of us!</p>
<ul>
    <li><a href="https://discord.gg/aYwysrb66b" target="_blank" rel="nofollow">Journal Limpet Discord</a></li>
    <li><a href="https://discord.gg/0uwCh6R62aQ0eeAX" target="_blank" rel="nofollow">The EDCD Discord</a></li>
    <li><a href="https://github.com/itssimple/journal-limpet" target="_blank" rel="nofollow">Our GitHub repository</a></li>
    <li><a href="https://twitter.com/JournalLimpet" target="_blank" rel="nofollow">Journal Limpet twitter</a></li>
    <li><a href="https://twitter.com/NoLifeKing85" target="_blank" rel="nofollow">NoLifeKing85 twitter</a></li>
</ul>

Journal-Limpet/Pages/FAQ.cshtml
@page
@model Journal_Limpet.Pages.FAQModel
@{
}
<h1>Frequently Asked Questions</h1>
<hr />
<h2>How many historical journals can I expect to get when I register on Journal Limpet?</h2>
It really depends on how active you are, but in accordance with how we're supposed to use the API from Frontier, we only pull the last 25 days (today - 25 days).
<br />
And if you don't login when we send the notification email that you need to login in for us to be able to download more journals, you might miss some journals in the gap.
<br />
<br />
<h2>Can I upload journals?</h2>
Not yet™️. But I will look at it at least, just gotta figure out a few things first.
<br />
<br />
<h2>How many journals will I be able to store? What is the maximum limit?</h2>
Uh.. I don't know yet. I bought a storage server to be able to handle up to ~16TB journals. So it'll probably be decided on as time goes on, and I figure out other ways to handle/store them.<br />
<br />
<br />
<h2>Are the journals that you store 100% complete?</h2>
Sadly not all journals are 100% complete if you'd compare them to your own local files (if you're on PC).<br />
I can't say why this is the case, because I'm only fetching the data that I can from the API, so what I have, is what I get from Frontier/Elite: Dangerous.<br />
<br />
<br />
<h2>Do you send data to &lt;THIS_SERVICE_NAME&gt;?</h2>
Oh boy, I don't know.. It depends if I have built an integration for it, which you can find under your <a asp-area="" asp-page="/Settings">Settings</a>.<br />
But currently we have integrations with:<br />
<br />
<ul>
    <li>EDDN - Journal Schema</li>
    <li>EDSM - Journal transfer</li>
    <li>Canonn Research - Journal transfer</li>
</ul>
.. and if you know some cool service that totally needs some awesome centralized journal data sent to them, feel free to open an issue at <a href="https://github.com/itssimple/journal-limpet/issues/new/choose" target="_blank">our GitHub</a>.
<br />
<br />
<h2>I downloaded the journals from Journal Limpet, but applications won't pick them up</h2>
Because of an issue with users accidentally downloading journals into their journal folder (from Elite Dangerous), applications started picking these up, so I've renamed them to avoid that, since it could potentially screw up some integrations and things.<br />
.. and we don't want that.. :).<br />
The old file format was: <code>Journal.YYMMDD000000.01.log</code><br />
The new file format is: <code>CAPIJournal.YYMMDD000000.01.log</code>

Journal-Limpet/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Main";
}

    <div class="jumbotron">
        @if(!User.Identity.IsAuthenticated)
        {
            await Html.RenderPartialAsync("_IndexUnauthenticated");
        }
        else
        {
            await Html.RenderPartialAsync("_IndexAuthenticated");
        }
        <hr />
        Current interval for fetching journals from the Frontier API: 10 minutes
    </div>

Journal-Limpet/Pages/Journals.cshtml
@page
@model Journal_Limpet.Pages.JournalsModel
@{
    ViewData["Title"] = "Journals";
}

<table class="table table-striped table-dark table-hover" id="journal-table" data-toggle="table" data-pagination="true">
    <thead>
        <tr>
            <th scope="col"
                data-field="JournalId"
                data-width="20" data-formatter="viewLinkFormatter">
                &nbsp;
            </th>
            <th scope="col"
                data-field="JournalDate"
                data-width="50" data-formatter="dateLinkFormatter">Journal Date</th>
            <th scope="col"
                data-field="NumberOfLines"
                data-width="50">Lines in journal</th>
            <th scope="col"
                data-field="CompleteEntry"
                data-width="50">
                <abbr title="Complete entry means that we can't get any more logs from that specific date">Complete entry</abbr>
            </th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
<hr />
<a href="~/api/journal/all-journals/download" rel="noopener" title="Download all your journals (.zip)">Download all journals as a ZIP-file</a>
@section Head
{
    <link rel="stylesheet" type="text/css" href="~/lib/bootstrap-table-master/bootstrap-table.min.css" />
}

@section Scripts
{
    <script type="text/javascript" src="~/lib/bootstrap-table-master/bootstrap-table.min.js"></script>

    <script type="text/javascript">
    var jt = $('#journal-table');
    (function() {
    var journalData = @Html.Raw(System.Text.Json.JsonSerializer.Serialize(Model.JournalItems));
    jt.bootstrapTable({ data: journalData });
    })();

    function dateLinkFormatter(value) {
        return `<a href="/api/journal/${value}/download" rel="noopener"><abbr title="Click to download the journal for ${value}">${value}</abbr></a>`
    }

        function viewLinkFormatter(value) {
            return `<a href="/ViewJournal?journal_id=${value}"><abbr title="Click to view the journal online">View</abbr></a>`
        }
    </script>
}

Journal-Limpet/Pages/LiveAccountLog.cshtml
@page
@model Journal_Limpet.Pages.LiveAccountLogModel
@{
    ViewData["title"] = "Live user log";
}

<div class="jumbotron">
    <h2>Live account log</h2>
    <hr />
    <pre class="terminal-window"><code class="log-window text-white"></code></pre>
</div>

<script src="~/js/live-account-log.js" asp-append-version="true"></script>

Journal-Limpet/Pages/Login.cshtml
@page
@model Journal_Limpet.Pages.LoginModel
@{
    ViewData["Title"] = "Login";
}

<h1>Login</h1>

Journal-Limpet/Pages/News.cshtml
@page "{title?}"
@model Journal_Limpet.Pages.NewsModel
@{
    ViewData["Title"] = "News";

    // Change this to work with files instead
    // Load news from /news-folder (markdown)

    string ReplaceVariables(string feedItem)
    {
        return feedItem
            .Replace("$rssUrl$", Url.ActionLink("NewsFeed", "Rss", null, HttpContext.Request.Scheme, HttpContext.Request.Host.ToString()));
    }
}
<h1>News and changes in Journal Limpet</h1>
<hr />
@foreach (var article in Model.Items)
{
    <h2>
        <a href="@article.Link" class="text-white">@article.Title</a>
        <br />
        <small class="text-muted">@article.PubDate.DateTime.ToString("yyyy-MM-dd") </small>
    </h2>
    @Html.Raw(ReplaceVariables(article.Description))
    <hr />
    <br />
}

Journal-Limpet/Pages/ReauthRequired.cshtml
@page
@model Journal_Limpet.Pages.ReauthRequiredModel
@{
    ViewData["Title"] = "Re-authentication required";
}

<h1>Re-authentication required</h1>

<p>It looks like your API token has expired and cannot be re-newed any longer.</p>
<p>To fix that, you have to login to Frontier again (through this <a href="/login" target="_self" title="Login through Frontier">link</a>)</p>

Journal-Limpet/Pages/ViewJournal.cshtml
@page
@model Journal_Limpet.Pages.ViewJournalModel
@{
    ViewData["Title"] = $"View journal - {Model.JournalItem.JournalDate.Date.ToShortDateString()}";

    var journalRows = Model.JournalContent.Split(new char[] {'\n'});
    long lineCounter = 0;
}
<style type="text/css">
    pre {
        white-space: normal;
        max-width: 100%;
    }

    .alternating-row {
        background-color: #191919;
    }
</style>
<div class="row">
    <div class="col-12 border border-light p-2">
    @foreach(var line in journalRows) {
        <pre class="text-white-50 m-0@(lineCounter % 2 == 0 ? " alternating-row" : "")">@line</pre>
        { lineCounter++; }
    }
    </div>
</div>